meta-metamong/meta-space

- .gitignore
> chore: gitignore 작성

- frontend/src/App.vue
- frontend/src/components/member/FindMember.vue
- frontend/src/pages/FindIdPw.vue
- frontend/src/pages/Home.vue
- frontend/src/router/index.js
> style: 들여쓰기 공간 변경

- frontend/src/App.vue
- frontend/src/components/member/LoginMember.vue
- frontend/src/components/member/SignUpMember.vue
- frontend/src/i18n.js
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/main.js
- frontend/src/pages/Login.vue
- frontend/src/pages/SignUp.vue
- frontend/src/router/index.js
> feat: 로그인, 회원가입 페이지 구현

- frontend/src/components/member/FindMember.vue
- frontend/src/i18n.js
- frontend/src/pages/FindIdPw.vue
> feat: 아이디 및 비밀번호 찾기 페이지 추가 개발

- frontend/src/App.vue
- frontend/src/components/common/Header.vue
- frontend/src/components/member/LoginMember.vue
- frontend/src/components/member/SignUpMember.vue
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/pages/FindIdPw.vue
- frontend/src/pages/Login.vue
- frontend/src/pages/SignUp.vue
- 라우팅
- 헤더의 로고 버튼을 클릭하면 메인 화면으로 이동합니다.
- 네비게이션의 로그인 박스를 클릭하면 로그인 화면으로 이동합니다.
- 네비게이션의 회원가입 박스를 클릭하면 회원가입 화면으로 이동합니다.
- 로그인 화면에서 아이디/비밀번호 찾기 버튼을 누르면 아이디/비밀번호 찾기 화면으로 이동합니다.
- 로그인 화면에서 회원가입 버튼을 누르면 회원가입 화면으로 이동합니다.
- 국제화
- 네비게이션의 목록들에 국제화를 적용했습니다.
- 네비게이션 가장 아래에 국제화 지역 변경 버튼을 클릭했습니다.
> feat: 국제화 설정

- frontend/src/components/common/Pagination.vue
페이지 뷰를 위한 공통 컴포넌트 구현
https://github.com/user-attachments/assets/5715bb27-80ab-4e8c-9761-d78f48ec0762
```
<Pagination :current-page="currentPage"
:start-page-no="startPageNo"
:end-page-no="endPageNo"
:is-previous-available="startPageNo !== 1"
:is-next-available="true"
@click-page-item="(page) => console.log('page=' + page)"
@click-previous="() => { startPageNo -= 10; endPageNo -= 10 }"
@click-next="() => { startPageNo += 10; endPageNo += 10 }" />
```
```v-bind``` (약어: ```:```)로 속성을 바인딩해 주어야 한다.
- ```current-page```: 처음 ```Pagination``` 컴포넌트가 렌더링되는 시점의 현재 페이지
- ```start-page-no```: ```Pagination```에 디스플레이될 페이지 목록 중 시작 페이지. inclusive
- ```end-page-no```: ```Pagination```에 디스플레이될 페이지 목록 중 종료 페이지. inclusive
- ```is-previous-available```: ```<``` 버튼 활성화 여부
- ```is-next-available```: ```>``` 버튼 …
> feat: Pagination 공통 컴포넌트 구현

- backend/src/main/java/com/metamong/mt/global/apispec/BaseResponse.java
- backend/src/main/java/com/metamong/mt/global/apispec/ErrorCodeSpecifiable.java
- backend/src/main/java/com/metamong/mt/global/apispec/ErrorResponse.java
BaseResponse, ErrorResponse 참고
> feat: 공통 응답 템플릿 정의

- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/config/WebConfig.java
- backend/src/main/java/com/metamong/mt/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/member/dto/request/FindMemberRequestDto.java
- backend/src/main/java/com/metamong/mt/member/service/IMemberService.java
- backend/src/main/java/com/metamong/mt/member/service/MemberService.java
- frontend/src/components/member/FindMember.vue
- controller에서 "/api/members/find-member" 엔드포인트로 요청을 받는다.
- POST 요청으로 FindMemberRequestDto 객체를 받게 된다.
- FindMemberRequestDto는 idOrPw, userid, name, email을 담고 있다.
- idOrPw는 아이디와 비밀번호 중 어느 것인지에 대한 정보를 담고 있다. (id or pw)
- idOrPw가 id인 경우 userid는 null이고, idOrPw가 pw인 경우 userid는 null이 아니다.
- name과 email은 idOrPw값 상관 없이 값이 전달된다.
> feat: 아이디 및 비밀번호 찾기(컨트롤러 - 서비스 연결)

- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/jwt/JwtAuthenticationFilter.java
- backend/src/main/java/com/metamong/mt/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/member/dto/request/MemberRequestDto.java
- backend/src/main/java/com/metamong/mt/member/dto/request/OwnerSignRequestDto.java
- backend/src/main/resources/application.properties
- frontend/src/apis/axios.js
- frontend/src/components/member/FindMember.vue
- frontend/src/components/member/LoginMember.vue
- api 공통 컴포넌트 개발
login, get, post, put, delete 5가지 함수 사용 가능
- api 연결
로그인, 아이디/비밀번호 찾기
> feat: api 관련 개발

- frontend/src/apis/axios.js
로그인 시 엑세스 토큰 저장 메서드를 호출하고, 로그아웃 시 엑세스 토큰 삭제 메서드를 호출해야 한다.
> feat: 엑세스 토큰 삭제 메서드 추가

- backend/src/main/java/com/metamong/mt/global/mail/MailType.java
- backend/src/main/java/com/metamong/mt/member/controller/MemberControllerAdvice.java
- backend/src/main/java/com/metamong/mt/member/exception/InvalidPasswordResetRequestException.java
- backend/src/main/java/com/metamong/mt/member/exception/MemberErrorCode.java
- backend/src/main/java/com/metamong/mt/member/repository/jpa/MemberRepository.java
- backend/src/main/java/com/metamong/mt/member/service/DefaultMemberService.java
- backend/src/main/java/com/metamong/mt/member/service/MemberService.java
- backend/src/main/java/com/metamong/mt/member/service/mailformatter/IdNotificationMailMessageFormatter.java
- backend/src/main/java/com/metamong/mt/member/service/mailformatter/PasswordResetLinkMailMessageFormatter.java
> feature: 메일 전송

- backend/src/main/java/com/metamong/mt/global/mail/MailType.java
- backend/src/main/java/com/metamong/mt/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/member/controller/MemberControllerAdvice.java
- backend/src/main/java/com/metamong/mt/member/exception/InvalidPasswordResetRequestException.java
- backend/src/main/java/com/metamong/mt/member/exception/MemberErrorCode.java
- backend/src/main/java/com/metamong/mt/member/exception/PasswordNotConfirmedException.java
- backend/src/main/java/com/metamong/mt/member/repository/jpa/MemberRepository.java
- backend/src/main/java/com/metamong/mt/member/service/DefaultMemberService.java
- backend/src/main/java/com/metamong/mt/member/service/MemberService.java
- backend/src/main/java/com/metamong/mt/member/service/mailformatter/IdNotificationMailMessageFormatter.java
- backend/src/main/java/com/metamong/mt/member/service/mailformatter/PasswordResetLinkMailMessageFormatter.java
> refactor: 공통 API 응답 형식 적용

- backend/src/main/java/com/metamong/mt/global/mail/MailType.java
- backend/src/main/java/com/metamong/mt/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/member/controller/MemberControllerAdvice.java
- backend/src/main/java/com/metamong/mt/member/exception/InvalidPasswordResetRequestException.java
- backend/src/main/java/com/metamong/mt/member/exception/MemberErrorCode.java
- backend/src/main/java/com/metamong/mt/member/exception/PasswordNotConfirmedException.java
- backend/src/main/java/com/metamong/mt/member/repository/jpa/MemberRepository.java
- backend/src/main/java/com/metamong/mt/member/service/DefaultMemberService.java
- backend/src/main/java/com/metamong/mt/member/service/MemberService.java
- backend/src/main/java/com/metamong/mt/member/service/mailformatter/IdNotificationMailMessageFormatter.java
- backend/src/main/java/com/metamong/mt/member/service/mailformatter/PasswordResetLinkMailMessageFormatter.java
> refactor: 서비스 객체 메소드 이름 변경

- db-schema/schema.sql
DB schema DDL을 SCM에서 관리하도록 DDL 스크립트 추가
> chore: DB schema DDL 추가

- backend/src/main/java/com/metamong/mt/global/jwt/JwtTokenProvider.java
Authroziation 헤더에서 토큰을 추출하고 Bearer 부분 떼서 access token만 추출
> refactor(JwtTokenProvider): Authorization에서 토큰 추출

- backend/src/main/java/com/metamong/mt/domain/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/domain/member/controller/MemberControllerAdvice.java
- backend/src/main/java/com/metamong/mt/domain/member/exception/IdEmailAleadyExistException.java
- backend/src/main/java/com/metamong/mt/domain/member/exception/errorcode/MemberErrorCode.java
- backend/src/main/java/com/metamong/mt/domain/member/repository/jpa/MemberRepository.java
- backend/src/main/java/com/metamong/mt/domain/member/service/DefaultMemberService.java
- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/config/WebConfig.java
- frontend/src/apis/axios.js
- frontend/src/components/member/LoginMember.vue
- 이미 등록되어 있는 회원 중 등록하려는 회원과 같은 id 또는 email을 사용하는 경우 다음을 응답합니다.
{
"errorName": "ID_EMAIL_ALEADY_EXIST",
"statusCode": 400,
"errorCode": "MEM005",
"message": "이미 존재하는 ID 또는 이메일입니다.",
"detail": null
}
> feat: 중복 회원가입 방지

- backend/src/main/java/com/metamong/mt/domain/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/FindMemberRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/repository/jpa/MemberRepository.java
- backend/src/main/java/com/metamong/mt/domain/member/service/DefaultMemberService.java
- backend/src/main/java/com/metamong/mt/domain/member/service/MemberService.java
- backend/src/main/java/com/metamong/mt/global/config/BeanConfig.java
- frontend/package-lock.json
- frontend/src/apis/axios.js
- frontend/src/components/member/SignUpMember.vue
- 아이디 및 이메일 중복 확인 통과 시 input과 button을 비활성화함.
> feat: 회원가입의 아이디 및 이메일 중복 확인

- backend/src/main/java/com/metamong/mt/domain/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/domain/member/exception/InvalidLoginRequestException.java
- backend/src/main/java/com/metamong/mt/domain/member/service/DefaultMemberService.java
- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/jwt/JwtAuthenticationFilter.java
- backend/src/test/java/com/metamong/mt/domain/member/controller/MemberControllerMockMvcTest.java
- backend/src/test/java/com/metamong/mt/domain/member/repository/jpa/MemberRepositoryTest.java
- backend/src/test/java/com/metamong/mt/domain/member/repository/mybatis/MemberMapperTest.java
- backend/src/test/java/com/metamong/mt/domain/member/service/DefaultMemberServiceTest.java
- backend/src/test/java/com/metamong/mt/testutil/DummyEntityGenerator.java
- backend/src/test/java/com/metamong/mt/testutil/MockFileUploader.java
> test: member 컴포넌트 테스트 코드 작성

- frontend/.env
- frontend/package-lock.json
- frontend/src/apis/axios.js
- .env 파일 추가
- 프론트에서 API 요청 시 BASE URL을 환경변수로 설정
> chore: 환경변수 설정

- backend/src/main/java/com/metamong/mt/global/config/BeanConfig.java
- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/config/constant/HttpRequestAuthorizationDefinition.java
- backend/src/main/resources/application.properties
- backend/src/test/java/com/metamong/mt/domain/member/controller/SecuredMemberControllerMockMvcTest.java
- 엔드포인트에 대한 권한 설정을 다른 클래스로 분리
- HTTP Method에 따른 엔드포인트에 대한 권한 설정
- MemberController.login에 대한 인증/인가 테스트 코드 작성
> refactor: 스프링 시큐리티 설정 리팩토링

- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/config/constant/HttpRequestAuthorizationDefinition.java
- backend/src/main/java/com/metamong/mt/global/jwt/JwtAuthenticationFilter.java
- backend/src/main/java/com/metamong/mt/global/jwt/JwtTokenProvider.java
- HttpRequestAuthorizationDefinition 상수 추가
NO_AUTH_REQUIRED_LIST(List<String>) 추가
> feat: 토큰 재발급 문제 해결

- db-schema/schema.sql
ERD 및 테이블 정의서가 변경되었기에 해당 변경사항을 DDL에 반영
- 테이블 정의서 내용을 DDL 스크립트에 반영
> chore: reflect table definition to DDL

- backend/src/main/java/com/metamong/mt/domain/reservation/controller/ReservationController.java
- backend/src/main/java/com/metamong/mt/domain/reservation/dto/response/ReservationResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/reservation/model/Reservation.java
- backend/src/main/java/com/metamong/mt/domain/reservation/repository/jpa/ReservationRepository.java
- backend/src/main/java/com/metamong/mt/domain/reservation/repository/mybatis/ReservationMapper.java
- backend/src/main/java/com/metamong/mt/domain/reservation/service/DefaultReservationService.java
- backend/src/main/java/com/metamong/mt/domain/reservation/service/ReservationService.java
- backend/src/main/java/com/metamong/mt/global/config/constant/HttpRequestAuthorizationDefinition.java
- backend/src/main/resources/mapper/reservation/ReservationMapper.xml
- frontend/src/App.vue
- frontend/src/components/common/Footer.vue
- frontend/src/components/common/Header.vue
- frontend/src/components/member/UpdateMember.vue
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/main.js
- frontend/src/pages/Reservation.vue
- frontend/src/router/index.js
- frontend/src/style.css
시설 이용자의 예약 목록 조회 구현
- 예약 목록 api 구현
- 예약 목록 화면 구현
- header, footer 위치 조정
> feat: 시설 이용자의 예약 목록 구현

- backend/src/main/resources/mapper/facility/FacilityMapper.xml
FacilityMapper.xml에서 NUMBER를 넣으니까 뭔가 오류가 발생. 그래 급하게 오류 해결 
- FacilityMapper.xml에서 NUMBER 제거
> HOTFIX: MyBatis 관련 오류 해결

- backend/src/main/java/com/metamong/mt/domain/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/ConsumerSignUpRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/ProviderSignUpRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/UpdateRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/model/Member.java
- frontend/src/apis/axios.js
- frontend/src/components/common/Footer.vue
- frontend/src/components/common/Header.vue
- frontend/src/pages/Login.vue
- frontend/src/router/index.js
- frontend/src/store/index.js
- 로그인 관련 기능 개발
- 로그인 및 로그아웃 api 연결
- 프론트 토큰 관리 수정
https://github.com/user-attachments/assets/0629a672-f2b5-45df-9bbf-d08cdb4addd3
> feat: 로그인 관련 프론트엔드 작업

- db-schema/schema.sql
변경된 테이블 정의서 반영
- 변경된 테이블 정의서 반영하여 DDL 작성
> chore: reflect table schema change

- frontend/src/App.vue
- frontend/src/components/common/AdminFooter.vue
- frontend/src/pages/Login.vue
admin@example.com 으로 로그인 시 admin 페이지 접속됨
- admin 페이지 header, home, footer 생성
> Admin page

- backend/src/main/java/com/metamong/mt/domain/facility/controller/FacilityController.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/mapper/AdditionalInfoUpdateMapperDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/mapper/FacilityUpdateMapperDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/mapper/ZoneUpdateMapperDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/FacilityDeleteRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/FacilityRegistrationRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/FacilityUpdateRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/exception/FacilityDeleteFailureException.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/AdditionalInfo.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/Facility.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/FacilityState.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/Zone.java
- backend/src/main/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapper.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/DefaultFacilityService.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/FacilityService.java
- backend/src/main/java/com/metamong/mt/domain/member/model/FctProvider.java
- backend/src/main/java/com/metamong/mt/domain/member/service/DefaultMemberService.java
- backend/src/main/java/com/metamong/mt/domain/member/service/MemberService.java
- backend/src/main/java/com/metamong/mt/global/apispec/CommonListUpdateRequestDto.java
- backend/src/main/resources/mapper/facility/FacilityMapper.xml
- backend/src/test/java/com/metamong/mt/domain/facility/controller/FacilityControllerMockMvcTest.java
- backend/src/test/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapperTest.java
- backend/src/test/java/com/metamong/mt/testutil/DummyEntityGenerator.java
- db-schema/schema.sql
시설을 수정하는 기능을 구현하였다네
```
{
"statusCode": 200,
"message": null,
"timestamp": "2025-02-07T15:38:17.7085756",
"content": {
"fctId": 1,
"fctName": "FACILITY",
"fctPostalCode": "54321",
"fctAddress": "Somewhere",
"fctDetailAddress": "Over the rainbow",
"fctLatitude": 37.513513,
"fctLongitude": 129.415341,
"fctTel": "02-2612-2555",
"catId": "300",
"catName": "Some category",
"fctGuide": "How can do that",
"isOpenOnHolidays": "Y",
"fctOpenTime": "08:00:00",
"fctClosetime": "18:00:00",
"fctState": "REGISTERED",
"fctImages": [
{
"fctImgDisplayOrder": 1,
"fctImgUrl": "http://localhost:8080/resources/images/zone-image1.jpg"
}
],
"zones": [
{
"zoneId": 1,
"zoneName": "ZONE1",
"maxUserCount": 50,
"hourlyRate": 5000,
"isSharedZone": "Y",
"zoneImgs": []
},
{
"zoneId": 2,
"zoneName": "ZONE2", …
```
> feat: 시설 수정 기능 구현

- backend/src/main/java/com/metamong/mt/domain/reservation/service/DefaultReservationService.java
- backend/src/test/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapperTest.java
세세한 버그 수정
- 컴파일 에러 수정
- FacilityMapperTest 에러 수정
> fix: trivial errors

- backend/src/main/java/com/metamong/mt/domain/member/controller/MemberController.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/EmailValidationCodeRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/EmailValidationCodeTransmissionRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/FindPasswordRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/dto/request/PasswordConfirmRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/member/service/DefaultEmailValidationService.java
- backend/src/main/java/com/metamong/mt/domain/member/service/EmailValidationService.java
- backend/src/main/java/com/metamong/mt/domain/member/service/MemberService.java
- backend/src/main/java/com/metamong/mt/global/config/constant/HttpRequestAuthorizationDefinition.java
- backend/src/test/java/com/metamong/mt/testutil/DummyEntityGenerator.java
- frontend/src/components/member/signup/InputEmail.vue
- frontend/src/components/member/signup/InputPassword.vue
- frontend/src/components/member/signup/InputRole.vue
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/pages/member/ChangePassword.vue
- frontend/src/pages/member/ConfirmPassword.vue
- frontend/src/pages/member/FindPassword.vue
- frontend/src/pages/member/Login.vue
- frontend/src/pages/member/Profile.vue
- frontend/src/pages/member/UpdateMember.vue
- frontend/src/router/index.js
- 회원 정보 수정 시 유효성 검증이 필요해서 추가했습니다.
- 회원 정보 수정, 비밀번호 재설정 시 유효성 검증이 추가되었습니다.
- 비밀번호 찾기를 위한 재설정 링크 발송 컨트롤러 메서드를 추가했습니다.
> feat: 회원 관련 프론트 구현

- backend/src/main/java/com/metamong/mt/global/config/BeanConfig.java
- backend/src/main/java/com/metamong/mt/global/config/RedisConfig.java
- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/file/local/LocalFilenameResolver.java
- frontend/src/components/member/signup/InputEmail.vue
- frontend/src/pages/member/SignUp.vue
- PROD 환경에서 작동되도록 수정했습니다.
- 백엔드의 config 파일
- 회원가입 시 프론트엔드 데이터 담기
> feat: 이메일 인증 API 연결

- frontend/package-lock.json
- frontend/src/components/facility/AdditionalInformation.vue
- frontend/src/components/facility/FacilityRegistrationInput.vue
- frontend/src/components/facility/ZoneRegistrationInput.vue
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/pages/facility/FacilityRegistration.vue
- frontend/src/router/index.js
시설 등록 페이지 뼈대 구현
https://github.com/user-attachments/assets/0bf391c3-65b6-41a4-b875-4c7764f7bd25
- 시설 등록 페이지 구현
> feat: 시설 등록 페이지

- backend/src/main/java/com/metamong/mt/domain/facility/model/Category.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/FacilityImage.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/ZoneImage.java
- backend/src/main/java/com/metamong/mt/global/config/WebConfig.java
- backend/src/main/java/com/metamong/mt/global/image/model/Image.java
- backend/src/main/java/com/metamong/mt/global/logging/LoggingAspect.java
- backend/src/main/java/com/metamong/mt/global/logging/LoggingInterceptor.java
AOP를 활용하여 로깅 구현. 디버깅, 메소드 실행 시간 측정에 사용
- LoggingAspect 구현
- LoggingInterceptor 구현
> feat: AOP 로깅 구현

- backend/src/main/java/com/metamong/mt/domain/facility/controller/FacilityController.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/constant/Order.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/constant/OrderBy.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/constant/SearchCondition.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/mapper/FacilityListMetadataMapperDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/FacilityListRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/response/FacilityListItemResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/response/FacilityListResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapper.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/DefaultFacilityService.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/FacilityService.java
- backend/src/main/resources/mapper/facility/FacilityMapper.xml
- backend/src/test/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapperTest.java
여러 조건에 따라 시설 목록을 가져올 수 있도록 동적 쿼리를 활용하여 시설 목록 가져오는 로직 구현
- 시설 목록 가져오기 구현
> feat: 시설 목록 가져오기 백엔드 로직

- db-schema/schema.sql
변경된 요구사항에 맞게 DB 스키마 변경
- fct_provider 테이블 칼럼 수정
- account 테이블 추가
> chore: update ddl

- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/FacilityRegistrationRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/ZoneRegistrationRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/response/ImageUploadUrlResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/FacilityState.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/DefaultFacilityService.java
- backend/src/main/java/com/metamong/mt/global/file/local/LocalFileUploader.java
- db-schema/sampledata.sql
- frontend/src/apis/axios.js
- frontend/src/components/facility/AdditionalInformation.vue
- frontend/src/components/facility/FacilityRegistrationInput.vue
- frontend/src/components/facility/ZoneRegistrationInput.vue
- frontend/src/pages/facility/FacilityRegistration.vue
시설 등록 API 연결 완료
- 파일 시스템에 저장됨
- GET 요청으로 파일을 가져올 수 있다
추후 prod 환경에서는 AWS S3에 올릴 수 있도록 하겠다
- 시설 등록 API 연결
- 파일 업로드
> feat: 시설 등록 API 연결

- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/FacilityRegistrationRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/request/ZoneRegistrationRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/response/ImageUploadUrlResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/model/FacilityState.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/DefaultFacilityService.java
- backend/src/main/java/com/metamong/mt/global/file/local/LocalFileUploader.java
- db-schema/sampledata.sql
- frontend/src/apis/axios.js
- frontend/src/components/facility/AdditionalInformation.vue
- frontend/src/components/facility/FacilityRegistrationInput.vue
- frontend/src/components/facility/ZoneRegistrationInput.vue
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/pages/facility/FacilityRegistration.vue
시설 등록 페이지 디자인
https://github.com/user-attachments/assets/1cdf8aac-46eb-4cf8-a25f-05c4a6f03bd5
- 시설 등록 페이지 디자인
- Zone 등록 페이지 디자인
- 추가 정보/서비스 페이지 디자인
> design: facility registration view

- backend/src/test/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapperTest.java
- backend/src/test/java/com/metamong/mt/global/file/local/LocalFileUploaderTest.java
테이블 스키마가 변경됨에 따라 (fct_provider 칼럼 개수 감소, account 테이블 생성) 테스트 코드의 SQL 불일치로 인한 에러 수정
- FacilityMapperTest 에러 수정
> fix: 테스트 코드에 있는 버그 수정

- frontend/src/components/facility/AdditionalInformation.vue
- frontend/src/components/facility/FacilityRegistrationInput.vue
- frontend/src/components/facility/ZoneRegistrationInput.vue
- frontend/src/pages/facility/FacilityRegistration.vue
https://github.com/user-attachments/assets/dc012d06-56b2-479d-b80a-f1015bbf3121
bootstrap-icons 사용
- 시설 등록에서 여러 버튼을 아이콘으로 변경
> design: 시설 등록 페이지 버튼을 아이콘으로 변경

- backend/src/main/java/com/metamong/mt/domain/facility/controller/FacilityController.java
- backend/src/main/java/com/metamong/mt/domain/facility/dto/response/FacilityListOfMemberResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapper.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/DefaultFacilityService.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/FacilityService.java
- backend/src/main/resources/mapper/facility/FacilityMapper.xml
- backend/src/test/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapperTest.java
- db-schema/sampledata.sql
- frontend/src/pages/facility/MyFacilityList.vue
일반 시설 목록 조회와 내가 등록한 시설 목록 조회에서 요구하는 데이터가 다르기 때문에 내 시설 목록만 조회하는 API 구현
- 내 시설 목록 조회 API 구현
> feat: 내 시설 목록 가져오기 API 구현

- frontend/src/components/facility/AdditionalInformation.vue
- frontend/src/components/facility/FacilityRegistrationInput.vue
- frontend/src/components/facility/ZoneRegistrationInput.vue
- frontend/src/pages/facility/FacilityRegistration.vue
- frontend/src/pages/reservation/ReservationList.vue
> refactor: 시설 등록 화면 수정

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/FctCard.vue
- frontend/src/components/common/Footer.vue
- frontend/src/components/common/SearchBox.vue
- frontend/src/main.js
- frontend/src/pages/Home.vue
- frontend/src/pages/Search.vue
- frontend/src/pages/facility/SearchedFacilityList.vue
- frontend/src/router/index.js
- 메인 화면과 검색 화면이 구현되었어요.
- 이제 하단 메뉴 좌측의 돋보기 아이콘을 클릭하면 검색 페이지로 들어가져요.
- 메인 페이지
- 검색 페이지
> feat: 프론트 페이지 구현

- frontend/src/components/common/SearchBox.vue
- frontend/src/pages/Search.vue
- frontend/src/pages/facility/SearchedFacilityList.vue
레디스를 통해 인기 검색어 기능을 구현했습니다.
- 인기 검색어가 불러와지지 않은 상태라면 예시 데이터가 나오게 했습니다.
- 검색 후에도 리스트업 된 페이지에서 검색어가 검색창에 유지됩니다.
> feat: 인기검색어

- backend/src/main/java/com/metamong/mt/domain/facility/controller/FacilityController.java
- backend/src/main/resources/mapper/facility/FacilityMapper.xml
- frontend/src/components/common/Footer.vue
- frontend/src/components/common/SearchBox.vue
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/pages/Search.vue
- frontend/src/pages/facility/SearchedFacilityList.vue
- frontend/src/router/index.js
말로 안 한다 동영상으로 한다
https://github.com/user-attachments/assets/dde5209f-e4fb-48f3-8a04-4404295e7575
https://github.com/user-attachments/assets/bd89723d-32b0-4fb1-bc7a-235bb413d66f
- SearchBox 컴포넌트 리팩토링
- 검색 버튼 클릭 시 "search" 이벤트 emit
- Search 페이지에서는 "search" 이벤트 emit 시 SearchedFacilityList 페이지로 이동
- SearchedFacilityList 페이지에서는 "search" 이벤트 emit 시 검색어를 가지고 검색
- 시설 목록 검색 API 연결
> feat: 시설 목록 검색 API 연결

- backend/src/main/java/com/metamong/mt/domain/facility/repository/mybatis/FacilityMapper.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/DefaultFacilityService.java
- backend/src/main/java/com/metamong/mt/domain/facility/service/FacilityService.java
- backend/src/main/java/com/metamong/mt/domain/report/controller/ReportController.java
- backend/src/main/java/com/metamong/mt/domain/report/controller/ReportControllerAdvice.java
- backend/src/main/java/com/metamong/mt/domain/report/dto/request/ReportProcessRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/report/dto/request/ReportRequestDto.java
- backend/src/main/java/com/metamong/mt/domain/report/dto/response/ReportResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/report/dto/response/ReportTypeResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/report/exception/ReportNotFoundException.java
- backend/src/main/java/com/metamong/mt/domain/report/exception/errorcode/ReportErrorCode.java
- backend/src/main/java/com/metamong/mt/domain/report/model/Report.java
- backend/src/main/java/com/metamong/mt/domain/report/model/constant/ReportType.java
- backend/src/main/java/com/metamong/mt/domain/report/repository/jpa/ReportRepository.java
- backend/src/main/java/com/metamong/mt/domain/report/service/DefaultReportService.java
- backend/src/main/java/com/metamong/mt/domain/report/service/ReportService.java
- backend/src/main/java/com/metamong/mt/global/config/constant/HttpRequestAuthorizationDefinition.java
- backend/src/main/resources/mapper/facility/FacilityMapper.xml
- frontend/src/store/index.js
신고 도메인을 구현했습니다.
- 신고
- 신고 목록 조회
- 신고 처리
- 신고 유형 목록 조회
> feat: 신고 도메인 구현

- Jenkinsfile
- backend/src/main/resources/application-prod.properties
- backend/src/main/resources/application.properties
- docker-compose-test.yml
- docker-compose.yml
- frontend/.dockerignore
- nginx/nginx.conf
Letsencrypt와 certbot을 활용하여 SSL 인증서 등록 및 HTTPS 설정
- NGINX reverse proxy 설정
- SSL 인증서 등록
- HTTPS 연결 설정
> chore: Jenkins 파이프라인 점검 및 HTTPS 설정

- frontend/src/components/admin/AdminMemberBen.vue
정지하는 회원 상세 테이블 추가
- 상세페이지 vue 변경
> admin 정지 페이지

- backend/src/main/java/com/metamong/mt/domain/reservation/controller/ReservationController.java
- backend/src/main/java/com/metamong/mt/domain/reservation/dto/response/FctReservationResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/reservation/repository/mybatis/ReservationMapper.java
- backend/src/main/java/com/metamong/mt/domain/reservation/service/DefaultReservationService.java
- backend/src/main/java/com/metamong/mt/domain/reservation/service/ReservationService.java
- backend/src/main/java/com/metamong/mt/global/config/constant/HttpRequestAuthorizationDefinition.java
- backend/src/main/resources/mapper/reservation/ReservationMapper.xml
- frontend/src/locales/en.json
- frontend/src/locales/ko.json
- frontend/src/pages/facility/FacilityReservationList.vue
- frontend/src/pages/facility/MyFacilityList.vue
- frontend/src/router/index.js
시설 제공자가 보유한 각 시설의 예약 정보 목록(보유 시설 목록에서 각 시설 클릭 시 이동)
- 각 시설의 예약 내역 조회
> feat: 각 시설의 예약 내역 조회

- backend/src/main/resources/mapper/admin/AdminMapper.xml
- frontend/src/components/admin/AdminMemberRefund.vue
- frontend/src/components/common/AdminFooter.vue
- frontend/src/store/index.js
관리자 환불 처리 화면 추가
- 마지막 메뉴 클릭 시 환불 처리 화면 나옵니다
> 관리자 환불 처리 화면

- frontend/src/App.vue
- frontend/src/style.css
> fix: 관리자 화면 비율 변경

- backend/src/main/java/com/metamong/mt/domain/notification/controller/NotificationController.java
- backend/src/main/java/com/metamong/mt/domain/notification/handler/ClientResolverHandshakeInterceptor.java
- backend/src/main/java/com/metamong/mt/domain/notification/repository/jpa/NotificationRepository.java
- backend/src/main/java/com/metamong/mt/domain/notification/repository/mybatis/NotificationMapper.java
- backend/src/main/java/com/metamong/mt/domain/notification/service/DefaultWebSocketNotificationService.java
- backend/src/main/java/com/metamong/mt/domain/notification/service/NotificationService.java
- backend/src/main/java/com/metamong/mt/global/config/SecurityConfig.java
- backend/src/main/java/com/metamong/mt/global/config/WebSocketConfig.java
- backend/src/main/resources/mapper/notification/NotificationMapper.xml
- backend/src/test/java/com/metamong/mt/domain/notification/repository/jpa/NotificationRepositoryTest.java
- backend/src/test/java/com/metamong/mt/domain/notification/repository/mybatis/NotificationMapperTest.java
- db-schema/sampledata.sql
- frontend/src/components/common/Header.vue
- frontend/src/pages/notification/NotificationList.vue
- frontend/src/store/index.js
알림 목록에 웹 소켓 연결해서 이제 알림 오면 잘 옵니다
https://github.com/user-attachments/assets/03e0b372-8c8d-4ab9-bed6-41400e93984f
- 알림 목록에 웹 소켓 연결
- 알림 목록 진입 시 알림 가져오기 (HTTP)
- 벨 버튼 클릭하면 알림 읽기
> feat: 알림 목록에 웹 소켓 연결

- backend/src/test/java/com/metamong/mt/domain/member/controller/MemberControllerTests.java
테스트 코드 중에 실패한 것 수정
- 테스트 코드 수정
> test: fix failed test

- backend/src/main/java/com/metamong/mt/domain/facility/dto/response/FacilityListItemResponseDto.java
- backend/src/main/resources/mapper/facility/FacilityMapper.xml
- frontend/src/components/common/Header.vue
- frontend/src/pages/Map.vue
- frontend/src/store/index.js
현재 위도, 경도 store에 저장
- 현재 위도, 경도 store에 저장
- 지도에 시설 전화번호 추가
> feat: 현재 위도, 경도 store에 저장

- frontend/src/components/common/Footer.vue
- frontend/src/pages/Home.vue
- frontend/src/pages/facility/SearchedFacilityList.vue
거리 계산 함수가 main에 추가되었습니다.
- 이제 거리 버튼 작동할 듯
- 됐으면 좋겠다.
> feat: 시설을 거리로 정렬하기

- backend/src/main/java/com/metamong/mt/domain/facility/dto/response/FacilityListOfMemberResponseDto.java
- backend/src/main/resources/mapper/facility/FacilityMapper.xml
- frontend/src/pages/facility/MyFacilityList.vue
예약 요청 중 : 노랑
등록 완료 : 초록
나머지 : 빨강
> feat: 시설 상태 불러올 때 테두리 색 변경

- frontend/src/components/facility/FacilityDetail.vue
- frontend/src/pages/facility/FacilityRegistration.vue
말 그대롭니다.
시설 등록 하면 시설 목록 페이지로 이동해요.
근데 이미지가 안뜨네..
> fix: 시설 등록 후 시설 리스트로 이동

- backend/src/main/java/com/metamong/mt/domain/notification/repository/jpa/CachingNotificationRepository.java
- backend/src/main/java/com/metamong/mt/domain/notification/repository/jpa/JpaNotificationRepository.java
- backend/src/main/java/com/metamong/mt/domain/notification/repository/jpa/NotificationRepository.java
- backend/src/main/java/com/metamong/mt/domain/notification/repository/mybatis/NotificationMapper.java
- backend/src/main/java/com/metamong/mt/domain/notification/service/DefaultWebSocketNotificationService.java
- backend/src/main/resources/mapper/notification/NotificationMapper.xml
- backend/src/test/java/com/metamong/mt/domain/notification/repository/jpa/NotificationRepositoryTest.java
- backend/src/test/java/com/metamong/mt/domain/notification/repository/mybatis/NotificationMapperTest.java
알림 개수에다가 Redis Caching 적용
- 알림 개수 카운트 시 Redis Caching 적용
- 알림 추가 시 Redis 업데이트
- 알림 삭제 시 Redis 업데이트
> feat: redis caching

- backend/src/main/java/com/metamong/mt/domain/admin/service/DefaultAdminService.java
- backend/src/main/resources/mapper/admin/AdminMapper.xml
- frontend/src/components/admin/AdminMemberSearch.vue
(변경사항에 대해서 설명해 주세요. 왜 이렇게 변경했는지 위주로 적어 주세요 - 이 괄호는 지워주세요/머지 후에 브랜치 삭제해 주세요)
- 변경사항1
> feat : 신고 로직 변경

- backend/src/main/resources/mapper/admin/AdminMapper.xml
- frontend/src/components/admin/AdminMemberBen.vue
- frontend/src/components/admin/DashBoard.vue
(변경사항에 대해서 설명해 주세요. 왜 이렇게 변경했는지 위주로 적어 주세요 - 이 괄호는 지워주세요/머지 후에 브랜치 삭제해 주세요)
- 변경사항1
> feat: 대시보드 오류 수정

- backend/src/main/java/com/metamong/mt/domain/admin/dto/response/FacilityReservationResponseDto.java
- backend/src/main/java/com/metamong/mt/domain/admin/dto/response/WeekReservationDto.java
- backend/src/main/resources/mapper/admin/AdminMapper.xml
- frontend/src/components/admin/AdminMemberRefund.vue
- frontend/src/components/admin/AdminSalesExport.vue
- frontend/src/components/admin/DashBoard.vue
(변경사항에 대해서 설명해 주세요. 왜 이렇게 변경했는지 위주로 적어 주세요 - 이 괄호는 지워주세요/머지 후에 브랜치 삭제해 주세요)
- 변경사항1
> feat: 매출조회 시설제공자명 수정

- frontend/src/components/admin/AdminSalesExport.vue
- frontend/src/components/admin/DashBoard.vue
(변경사항에 대해서 설명해 주세요. 왜 이렇게 변경했는지 위주로 적어 주세요 - 이 괄호는 지워주세요/머지 후에 브랜치 삭제해 주세요)
- 변경사항1
> feat : 대시보드 오류 수정
